// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBleNKZ2ieYMqCUES0HFJ3jfPz3TNBQRqc',
    appId: '1:363382812775:web:20bd6e671ba7a7baec24c2',
    messagingSenderId: '363382812775',
    projectId: 'fir-project-1340c',
    authDomain: 'fir-project-1340c.firebaseapp.com',
    storageBucket: 'fir-project-1340c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vA8Q8pT0Ej2ulTZ1x99n_1skTqa0yvY',
    appId: '1:363382812775:android:ba0725afb8f5c5d7ec24c2',
    messagingSenderId: '363382812775',
    projectId: 'fir-project-1340c',
    storageBucket: 'fir-project-1340c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgTvgCPmW6r5fmSRbD9v76NPKRyDr52ek',
    appId: '1:363382812775:ios:4580141993d4e5faec24c2',
    messagingSenderId: '363382812775',
    projectId: 'fir-project-1340c',
    storageBucket: 'fir-project-1340c.appspot.com',
    iosBundleId: 'com.example.learningfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgTvgCPmW6r5fmSRbD9v76NPKRyDr52ek',
    appId: '1:363382812775:ios:4580141993d4e5faec24c2',
    messagingSenderId: '363382812775',
    projectId: 'fir-project-1340c',
    storageBucket: 'fir-project-1340c.appspot.com',
    iosBundleId: 'com.example.learningfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBleNKZ2ieYMqCUES0HFJ3jfPz3TNBQRqc',
    appId: '1:363382812775:web:02805a1925026925ec24c2',
    messagingSenderId: '363382812775',
    projectId: 'fir-project-1340c',
    authDomain: 'fir-project-1340c.firebaseapp.com',
    storageBucket: 'fir-project-1340c.appspot.com',
  );
}
